trigger:
  branches:
    include:
    - main
  paths:
    include:
    - azure-devops/agents
    - azure-devops/ado/build-single-arch-ado-agent.yaml

pr: none

resources:
  repositories:
  - repository: platform-ops
    type: github
    name: qbituniverse/platform-ops
    endpoint: qbituniverse

stages:
- stage: DockerBuildAmd64
  displayName: 'Build Docker Image for ADO Agent - amd64'
  pool:
    name: self-hosted-ado-agents
    demands:
    - agent.name -equals ado-agent-amd64
  variables:
    imageDockerfile: azure-devops/agents/Dockerfile-ado-agent-amd64
    imageRepository: qbituniverse/ado-agent
    imageTag: $(imageVersion).$(Build.BuildId)
    imageVersion: 'N/A'
  jobs:
  - job: DockerBuildAmd64
    displayName: 'Build Docker Image for ADO Agent - amd64'
    timeoutInMinutes: 0
    steps:
    - template: azure-devops/builds/assign-build-number.yaml@platform-ops
      parameters:
        imageDockerfile: $(imageDockerfile)
        imageTag: $(imageTag)

    - template: azure-devops/builds/build-push-docker-image-single-arch.yaml@platform-ops
      parameters:
        imageRepository: $(imageRepository)
        imageDockerfile: $(imageDockerfile)
        imageTag: $(imageTag)-amd64
        addLatestTag: false

    - template: azure-devops/builds/build-push-docker-image-single-arch.yaml@platform-ops
      parameters:
        imageRepository: $(imageRepository)
        imageDockerfile: $(imageDockerfile)
        imageTag: latest-amd64
        addLatestTag: false

- stage: DockerBuildArm64
  displayName: 'Build Docker Image for ADO Agent - arm64'
  pool:
    name: self-hosted-ado-agents
    demands:
    - agent.name -equals ado-agent-arm64
  variables:
    imageDockerfile: azure-devops/agents/arm64/Dockerfile-ado-agent-arm64
    imageRepository: qbituniverse/ado-agent
    imageTag: $(imageVersion).$(Build.BuildId)
    imageVersion: 'N/A'
  jobs:
  - job: DockerBuildArm64
    displayName: 'Build Docker Image for ADO Agent - arm64'
    timeoutInMinutes: 0
    steps:
    - template: azure-devops/builds/assign-build-number.yaml@platform-ops
      parameters:
        imageDockerfile: $(imageDockerfile)
        imageTag: $(imageTag)

    - template: azure-devops/builds/build-push-docker-image-single-arch.yaml@platform-ops
      parameters:
        imageRepository: $(imageRepository)
        imageDockerfile: $(imageDockerfile)
        imageTag: $(imageTag)-arm64
        addLatestTag: false

    - template: azure-devops/builds/build-push-docker-image-single-arch.yaml@platform-ops
      parameters:
        imageRepository: $(imageRepository)
        imageDockerfile: $(imageDockerfile)
        imageTag: latest-arm64
        addLatestTag: false